@startuml

top to bottom direction
skinparam dpi 200
allow_mixing
scale 400 width

skinparam ActivityDiamondBackgroundColor #RoyalBlue
skinparam ArrowColor #SlateGrey   
skinparam ArrowFontColor #RoyalBlue
skinparam ArrowFontColor #SlateGrey  
skinparam ArrowFontSize 12
skinparam ArrowMessageAlignment left
skinparam BoxPadding 10
skinparam linetype ortho
skinparam nodesep 90
skinparam ranksep 40
skinparam roundcorner 5
skinparam sequenceArrowThickness 2
skinparam TitleFontSize 20


title FHIR Consent instances when patient consent is pending

frame "Representation of limited provisional consent when patient's signed form pending but not received" as F {

  object "consent to treatment\n<size:16>**:CONSENT**" as TREATCONSENT #DodgerBlue {
    * status: ""<color:Orange>**#proposed**</color>""
    * scope: ""**#treatment**""
    * policy: reference to regs/leg.
  }

  object "treatment provision" as TP #LightBlue/DodgerBlue  {
    * type: ""<color:GreenYellow>**#permit**""
    * period: 
      **""2023-01-21"" <sup>4</sup> to ""..""**
  }

  object "consent to collect/share data\n<size:16>**:CONSENT**" as DATACONSENT #DodgerBlue {
    * status: ""<color:Orange>**#proposed**</color>""
    * scope: ""**#patient-privacy**""
    * policy: reference to regs/leg.
  }

  object "data access permit provision" as DAP #LightBlue/DodgerBlue  {
    * type: ""<color:DarkRed>**#deny**""
    * period: 
      **""2023-01-21"" <sup>4</sup> to ""..""**
  }

  ' resources in other repos
  object "NHI patient\n**:PATIENT**" as PATIENT <<logical reference>> #SkyBlue {
    * logical id: NHI
  }

  object "RF Secondary Prevention Service\n(custodian org)\n:**ORGANIZATION**" as HPI <<logical reference>> #GhostWhite {
    * HPI Org Id: ""GnXnnn""
  }

  frame "<size:12>Covered resources all security-labelled '""R""' (Restricted)<sup>2</sup>" as COVERED #GhostWhite/OrangeRed {
    object "planned appointments, etc.\n<size:14>**:CAREPLAN**" as R1 #LightGray
    object "condition severity and specifics\n<size:14>**:CONDITION**" as R2 #LightGray
    object "appointments\n<size:14>**:ENCOUNTER**" as R3 #LightGray
    object "preferences, health assessments\n<size:14>**:QUESTIONNAIRERESPONSE**" as R4 #LightGray
    object "diagnosis detail\n<size:14>**:OBSERVATION**" as R5 #LightGray
  }
}

' positioning
TREATCONSENT -[hidden]d- TP
TP -[hidden]d- DATACONSENT


' connectors
DAP "**.data.reference**<sup>2</sup>" -[thickness=3,#RoyalBlue]--{ COVERED 

TREATCONSENT ".patient<sup>3</sup>" -[dotted,#SkyBlue,norank]-> PATIENT
TREATCONSENT -[norank]-* TP : "".provision""
TREATCONSENT ".organization\n**HPI org. ref**<sup>1</sup>" -[dashed,#Black]l-> HPI

DATACONSENT ".patient" -[dotted,#SkyBlue,norank]-> PATIENT
DATACONSENT -* DAP : "".provision""
DATACONSENT ".organization\n**HPI org. ref**<sup>1</sup>" -[dashed,#Black]u-> HPI 

legend bottom
  **Notes**
  1. ""Consent.organization"" identifies a specific //RF Secondary Prevention Service// which:
      \ta. Coordinates treatment for patients in that district/region, and
      \tb. Operates the consent process (forms etc.), and
      \tc. Is the custodian of data collected from these patients.
   2. This list of referenced FHIR instances is maintained by Mulesoft integration.
      - All these covered FHIR instances will have **""R"" security labels** attached while the consent
         is provisional.  The labels will be removed when patient data consent is confirmed.
  3. All Consent instances identify via "".patient"" the **person the consent applies to**.
  4. Start date is date consent provisionally assumed by the RF Secondary Prevention Service; 
      End date is empty (provision doesn't expire).

endlegend

footer "Health NZ/Te Whatu Ora.  FHIR instance data model generated from PlantUML source on %date('dd/MM/yyyy')"

@enduml