@startuml obj-FHIR-data-consent-provisional

top to bottom direction
skinparam dpi 200
allow_mixing
scale 400 width

skinparam ActivityDiamondBackgroundColor #RoyalBlue
skinparam ArrowColor #SlateGrey   
skinparam ArrowFontColor #RoyalBlue
skinparam ArrowFontColor #SlateGrey  
skinparam ArrowFontSize 12
skinparam ArrowMessageAlignment left
skinparam BoxPadding 10
skinparam linetype ortho
skinparam nodesep 90
skinparam ranksep 40
skinparam roundcorner 5
skinparam sequenceArrowThickness 2
skinparam TitleFontSize 20


title FHIR Consent instances for patient opted-out of everything on June 23 2023

!procedure $Coding($Alias,$System,$Code,$Display)
  object "<color:GhostWhite>$System" as $Alias #MediumPurple {
    <color:GhostWhite><size:11>**$Code**-$Display
  }
!endprocedure

object "consent to treatment\n<size:16>**:CONSENT**" as TREATCONSENT #DodgerBlue {
  * status: ""<color:GreenYellow>**#active**""
  * scope: ""**#treatment**""
  * dateTime: ""2023-01-21""
  * policy: reference to Health Act / standing order
}

object "treatment provision" as TP #GhostWhite/LightBlue  {
  * type: ""<color:Red>**#deny**""
  * period: 
    ""2023-06-23"" to ""2026-01-20""
}

object "consent to collect/share data\n<size:16>**:CONSENT**" as DATACONSENT #DodgerBlue {
  * status: ""<color:GreenYellow>**#active**""
  * scope: ""**#patient-privacy**""
  * dateTime: ""2023-01-21""
  * policy: reference to NZ Privacy Act / HIPC
}

object "data access permit provision" as DAP #GhostWhite/LightBlue  {
  * type: ""<color:Red>**#deny**""
  * period: 
    ""2023-06-23"" to ""2026-01-20""
}

object "exception access permit provision" as EDAP <<nested>> #GhostWhite/LightBlue  {
  * type: ""**#permit**""
  * period: 
    ""2023-01-21"" to ""2026-01-20""
}

object "All RF secondary prevention svcs\n**:CARETEAM**<sup>5</sup>" as CARETEAM <<canonical definition>> #GhostWhite/OrangeRed

object "**provision.actor**" as ORGACTOR #GhostWhite/LightBlue {
  * actor.role: ""<color:#IndianRed>**#datacollector**""
}

object "**provision.actor**" as SUBJECTACTOR #GhostWhite/LightBlue {
  * actor.role: ""<color:#IndianRed>**#datasubject**""
}

' resources in other repos
object "NHI patient\n**:PATIENT**" as PATIENT <<logical reference>> #SkyBlue {
  * logical id: NHI
}

object "Rheumatic fever prevention service\n(custodian org):**ORGANIZATION**" as HPI <<logical reference>> #SkyBlue {
  * HPI Org Id: ""GnXnnn""
}

frame "<size:12>Resource instances protected by data consent <sup>2</sup>" as COVERED {
'  object "patient's responses\n<size:12>**:QUESTIONNAIRERESPONSE**" as QRC #LightSalmon
  object "<size:14>**:CAREPLAN**" as R1 #LightGray
  object "<size:14>**:CONDITION**" as R2 #LightGray
  object "<size:14>**:ENCOUNTER**" as R3 #LightGray
  object "another FHIR instance x<sub>1</sub>\n**<size:15>:X**" as Another1 #LightGray
  object "another FHIR instance y<sub>2</sub>\n**<size:15>:Y**" as Another2 #LightGray
}

' positioning
TREATCONSENT -[hidden]d- TP
TP -[hidden]d- DATACONSENT

' connectors
DAP "**.data.reference**<sup>2</sup>" -[thickness=3,#RoyalBlue]d----{ COVERED 
DAP -r-* SUBJECTACTOR
DAP -d-* EDAP
EDAP --* ORGACTOR

TREATCONSENT ".patient<sup>3</sup>" -[dotted,#SkyBlue,norank]---> PATIENT
TREATCONSENT -[norank]-* TP : "".provision""
TREATCONSENT -[dashed,#Black]l-> HPI: .organization\n**HPI org. ref**<sup>1</sup>

DATACONSENT ".patient" -[dotted,#SkyBlue]r--> PATIENT
DATACONSENT -d--* DAP : "".provision""
DATACONSENT -[dashed,#Black]--> HPI: .organization\n**HPI org. ref**<sup>1</sup>

ORGACTOR -[thickness=3,#RoyalBlue]-> CARETEAM: .actor.reference
SUBJECTACTOR  -[dotted,#SkyBlue,norank]--> PATIENT: .actor.reference

CARETEAM "\n.participant.member.reference" -[dashed,#SkyBlue]l--{ HPI: > 


legend bottom
  **Notes**
  1. ""Consent.organization"" identifies a specific //RF Secondary Prevention Service// which:
      \ta. Coordinates treatment for patients in that district/region, and
      \tb. Operates the consent process (forms etc.), and
      \tc. Is the custodian of data collected from these patients.
  2. This list of referenced FHIR instances is maintained by Mulesoft integration on 
        behalf of the RFCCS application which is used by the various RF Secondary Prevention
        Service orgs to maintain the register.
  3. All Consent instances identify via "".patient"" the person the consent applies to.
  4. FHIR Consent resource instances are not subject to consent-based access control.
  5. This CareTeam actor describes data access permission for Secondary Prevention Service orgs only.
  6. A **'""#deny""'** code represents patient's withdrawal of the applicable permission scope.
endlegend

footer "Health NZ/Te Whatu Ora.  FHIR instance data model generated from PlantUML source on %date('dd/MM/yyyy')"

@enduml