@startuml obj-FHIR-data-consent-active

top to bottom direction
skinparam dpi 200
allow_mixing
scale 400 width

skinparam ActivityDiamondBackgroundColor #RoyalBlue
skinparam ArrowColor #SlateGrey   
skinparam ArrowFontColor #RoyalBlue
skinparam ArrowFontColor #SlateGrey  
skinparam ArrowFontSize 12
skinparam ArrowMessageAlignment left
skinparam BoxPadding 10
skinparam linetype ortho
skinparam nodesep 30
skinparam ranksep 30
skinparam roundcorner 5
skinparam sequenceArrowThickness 2

title FHIR instance data for active patient consent

!procedure $Coding($Alias,$System,$Code,$Display)
  object "<color:GhostWhite>$System" as $Alias #MediumPurple {
    <color:GhostWhite><size:11>**$Code**-$Display
  }
!endprocedure

  
object "consent to treatment\n<size:16>**:CONSENT**" as TREATCONSENT #DodgerBlue {
  * status: ""**#active**""
  * scope: ""**#treatment**""
  * dateTime: ""2023-01-21""
  * policy: reference to Health Act \n/ standing order
}

object "treatment permit provision" as TAP #GhostWhite/LightCoral  {
  * type: ""#permit""
  * period: ""2023-01-21 to 2026-01-20""
}

object "consent to collect/share data\n<size:16>**:CONSENT**" as DATACONSENT #DodgerBlue {
  * status: ""**#active**""
  * scope: ""**#patient-privacy**""
  * dateTime: ""2023-01-21""
  * policy: reference to NZ Privacy Act / HIPC
}

object "data access permit provision" as DAP #GhostWhite/LightCoral  {
  * type: ""#permit""
  * period: ""2023-01-21 to 2026-01-20""
}

frame "<size:12>Resource instances protected by data consent <sup>2</sup>" as COVERED {
  object "<size:14>**:CAREPLAN**" as R1 #LightGray
  object "<size:14>**:CONDITION**" as R2 #LightGray
  object "<size:14>**:ENCOUNTER**" as R3 #LightGray
  object "other FHIR instance x<sub>1</sub>\n**<size:15>:X**" as Another1 #LightGray
  object "other FHIR instance y<sub>2</sub>\n**<size:15>:Y**" as Another2 #LightGray
}

' resources in other repos
object "NHI patient\n:**PATIENT**" as PATIENT <<logical reference>> #SkyBlue {
  * logical id: NHI
}

object "RF Prevention Service\n:**ORGANIZATION**" as HPI <<logical reference>> #SkyBlue {
  * HPI Org Id: ""GnXnnn""
}

' positioning
TREATCONSENT -[hidden]d- TAP
TAP -[hidden]d- DATACONSENT

' connectors
DAP "**.data.reference**<sup>2</sup>" -[thickness=3,#RoyalBlue]-{ COVERED 

TREATCONSENT -[dashed,#Black,norank]---> HPI: .organization\n**HPI Org. ref**<sup>1</sup>
TREATCONSENT ".patient<sup>3</sup>" -[dotted,#SkyBlue,norank]--> PATIENT
TREATCONSENT -[norank]-* TAP : "".provision""

DATACONSENT -[dotted,#SkyBlue]l---> PATIENT
DATACONSENT -d-* DAP : "".provision""
DATACONSENT -[dashed,#Black]--> HPI: .organization\n**HPI Org. ref**<sup>1</sup>

legend bottom
  **Notes**
  1. ""Consent.organization"" identifies a specific //RF Secondary Prevention Service// which:
      \ta. Coordinates treatment for patients in that district/region, and
      \tb. Operates the consent process (forms etc.), and
      \tc. Is the custodian of data collected from these patients.
  2. This list of referenced FHIR instances is maintained by Mulesoft integration on behalf of the  
      RFCCS application which is used by the various RF Secondary Prevention Service orgs to maintain the register.
  3. All Consent instances identify via "".patient"" the person the consent applies to 
  4. Instances of the FHIR Consent resource type itself are accessible to all authorized API consumers.
endlegend


footer "Health NZ/Te Whatu Ora.  FHIR instance data model generated from PlantUML source on %date('dd/MM/yyyy')"

@enduml