@startuml obj-FHIR-data-consent-givenonbehalf

top to bottom direction
skinparam dpi 200
allow_mixing
scale 400 width

skinparam ActivityDiamondBackgroundColor #RoyalBlue
skinparam ArrowColor #SlateGrey   
skinparam ArrowFontColor #RoyalBlue
skinparam ArrowFontColor #SlateGrey  
skinparam ArrowFontSize 12
skinparam ArrowMessageAlignment left
skinparam BoxPadding 10
skinparam linetype ortho
skinparam nodesep 90
skinparam ranksep 40
skinparam roundcorner 5
skinparam sequenceArrowThickness 2
skinparam TitleFontSize 20


' create a object with security label
' usage: $SEC_LABELLED_INSTANCE(R1,"<object name>","<label Id")
!unquoted procedure $SEC_LABELLED_INSTANCE($Alias, $displayText="",$label="")
  object "$displayText" as $Alias {
    <color:Red><&flag> <Color:Black>security label: ""<size:16><color:DarkRed>$label""
  }
!endprocedure

title FHIR Consent instance data - on-behalf consent

frame "Representation of patient consent when given on behalf by a related person" as F {

  !procedure $Coding($Alias,$System,$Code,$Display)
    object "<color:GhostWhite>$System" as $Alias #MediumPurple {
      <color:GhostWhite><size:11>**$Code**-$Display
    }
  !endprocedure

  object "<size:16>**Consent to treatment**\n<size:16>**:CONSENT**" as TREATCONSENT #DodgerBlue {
    * status: ""<color:GreenYellow>**#ACTIVE**""
    * scope: ""**#treatment**""
    * policy: reference to regs/leg.
  }

  object "treatment provision" as TP #Brown/SandyBrown  {
    * type: ""<color:GreenYellow>**#PERMIT**""
    * period: 
      **""2023-01-21"" to ""2026-01-20""**
  }

  object "<size:16>**Consent to collect/share data**\n<size:16>**:CONSENT**" as DATACONSENT #DodgerBlue {
    * status: ""<color:GreenYellow>**#ACTIVE**""
    * scope: ""**#patient-privacy**""
    * policy: reference to regs/leg.
  }

  object "data access provision" as DAP #Brown/SandyBrown  {
    * type: ""<color:GreenYellow>**#PERMIT**""
    * period: 
      **""2023-01-21"" to ""2026-01-20""**
  }

  object "person giving consent\n<size:14>**:RELATEDPERSON**<sup>4</sup>" as RP1 <<contained>> #LightYellow {
    * name.given: **Beryl**
    * name.family: **Hackett**
    * relationship: **""#PRN""**
  }

  object "person giving consent\n<size:14>**:RELATEDPERSON**<sup>4</sup>" as RP2 <<contained>> #LightYellow {
    * name.given: **Beryl**
    * name.family: **Hackett**
    * relationship: **""#PRN""**
  }

  ' resources in other repos
  object "NHI patient\n**:PATIENT**" as PATIENT <<logical reference>> #SkyBlue {
    * logical id: NHI
  }

  object "RF Secondary Prevention Service\n(custodian org)\n:**ORGANIZATION**" as HPI <<logical reference>> #GhostWhite {
    * HPI Org Id: ""GnXnnn""
  }

  frame "Patient data covered by data access provision<sup>2</sup>" as COVERED #LightGreen {
    $SEC_LABELLED_INSTANCE(R1,"planned appointments, etc.\n<size:14>**:CAREPLAN**"                    ,"R (restricted)")
    $SEC_LABELLED_INSTANCE(R2,"condition severity and specifics\n<size:14>**:CONDITION**"             ,"R (restricted)")
    $SEC_LABELLED_INSTANCE(R3,"appointments\n<size:14>**:ENCOUNTER**                               "  ,"R (restricted)")
    $SEC_LABELLED_INSTANCE(R4,"preferences, health assessments\n<size:14>**:QUESTIONNAIRERESPONSE**"  ,"R (restricted)")
    $SEC_LABELLED_INSTANCE(R5,"diagnosis detail\n<size:14>**:OBSERVATION**                         "  ,"R (restricted)")
    R3 -[hidden]u- R1
    R4 -[hidden]u- R2
    R5 -[hidden]u- R4

  }
}

' positioning
TREATCONSENT -[hidden]d- TP
TP -[hidden]d- DATACONSENT


' connectors
DAP "**.data.reference**<sup>2</sup>" -[thickness=3,#RoyalBlue]--{ COVERED 

TREATCONSENT ".patient<sup>3</sup>" -[dotted,#SkyBlue,norank]-> PATIENT
TREATCONSENT -[norank]-* TP : "".provision""
TREATCONSENT ".organization\n**HPI org. ref**<sup>1</sup>" -[dashed,#Black]l-> HPI
TREATCONSENT -d-* RP1: <color:#Black>.performer<sup> 4</sup>

DATACONSENT ".patient" -[dotted,#SkyBlue,norank]-> PATIENT
DATACONSENT -* DAP : "".provision""
DATACONSENT ".organization\n**HPI org. ref**<sup>1</sup>" -[dashed,#Black]u-> HPI 
DATACONSENT -d-* RP2: <color:#Black>.performer<sup> 4</sup>

RP1 -[dotted,#SkyBlue,norank]--> PATIENT
RP2 -[dotted,#SkyBlue,norank]---> PATIENT

legend bottom
  **Notes**
  1. ""Consent.organization"" identifies a specific //RF Secondary Prevention Service// which:
      \ta. Coordinates treatment for patients in that district/region, and
      \tb. Operates the consent process (forms etc.), and
      \tc. Is the custodian of data collected from these patients.
  2. This list of referenced FHIR instances is maintained by Mulesoft integration.
  3. All Consent instances identify via "".patient"" the **person the consent applies to**.
  4. Note the RelatedPerson instance is contained within AND linked from (via .performer) the Consent instance.

endlegend

footer "Health NZ/Te Whatu Ora.  FHIR instance data model generated from PlantUML source on %date('dd/MM/yyyy')"

@enduml